name: "Terraform GitHub Actions"
on:
  - pull_request
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
        env:
          GITHUB_TOKEN: ${{ secrets.ghpat }}
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{ secrets.ghpat }}
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "validate"
        env:
          GITHUB_TOKEN: ${{ secrets.ghpat }}
      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
        env:
          GITHUB_TOKEN: ${{ secrets.ghpat }}
          TF_VAR_tenant_id: ${{ secrets.TENANTID}}
          TF_VAR_subsription_id: ${{ secrets.SUBSCRIPTIONID}}
          TF_VAR_client_id: ${{ secrets.CLIENTID}}
          TF_VAR_client_secret: ${{ secrets.CLIENTSECRET}}
